Fixes of MotionPlanning package structure and description
HexapodBionik/MotionPlanning pull request #15
Opened 2024-03-17 21:52 UTC by VisteK528

2024-03-18 13:34 UTC, dbarania requested changes
Zaznaczyłem ci 3 miejsca w importach testów, jak puścisz tam pytesta czy z konsoli czy vs code rzuca  ci błędami, że nie jest w stanie znaleźć modułu kinematics 
![image](https://github.com/HexapodBionik/MotionPlanning/assets/128425202/e6fdbb2d-3027-4472-b39b-9dd0d9da7b35)

2024-03-18 13:34 UTC, dbarania commented on kinematics/tests/test_kinematics_initialization.py
> +from kinematics.kinematics_exceptions import InvalidInitVector
To coś rzuca błędami przy pyteście
![image](https://github.com/HexapodBionik/MotionPlanning/assets/128425202/57bef125-a150-491e-ae0b-43a51ffa4e1e)

2024-03-18 13:34 UTC, dbarania commented on kinematics/tests/test_of_forward_kinematics.py
> +from kinematics.kinematics_solvers import KinematicsSolver
Tak samo

2024-03-18 13:34 UTC, dbarania commented on kinematics/tests/test_of_inverse_kinematics.py
> +from kinematics.kinematics_solvers import KinematicsSolver
tak samo

2024-03-24 16:44 UTC, VisteK528 commented
Sprawdziłem, wszystkie testy przechodzą, więc proponuję mergować

2024-03-24 17:39 UTC, antoniprzybylik approved these changes

2024-03-24 18:33 UTC, dbarania approved these changes

2024-03-24 21:41 UTC, merged